stages:
  - Tests

PHP-CS-Fixer:
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  stage: Tests
  cache:
    key: vendor
    paths:
      - vendor
  before_script:
    - composer install --ignore-platform-reqs
  script:
    - vendor/bin/php-cs-fixer fix -v --dry-run

PHPUnit:
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  stage: Tests
  cache:
    key: vendor
    paths:
      - vendor
  before_script:
    - composer install --ignore-platform-reqs
  script:
    - vendor/bin/phpunit --coverage-text
